// ========== BUILD REPORT ==========
function buildReport() {
  console.log("بناء التقرير...");
  
  const report = document.getElementById('report');
  if (!report) return;
  
  // حفظ حالة العرض الحالية
  const currentTab = document.querySelector('.tab-content[style*="block"]');
  
  // عرض كل المحتويات مؤقتاً
  document.querySelectorAll('.tab-content').forEach(tab => {
    tab.style.display = 'block';
  });
  
  // بناء محتوى التقرير
  report.innerHTML = `
    <div style="background:white; color:black; padding:30px; font-family:Arial, sans-serif;">
      <div style="text-align:center; border-bottom:2px solid #ccc; padding-bottom:20px; margin-bottom:30px;">
        <h1 style="color:#1f2937; margin:0;">NDC PROJECT REPORT</h1>
        <p style="color:#6b7280;">Generated on: ${new Date().toLocaleString()}</p>
        <p style="color:#6b7280;">User: ${sessionStorage.getItem('username') || 'Unknown'}</p>
      </div>
      
      <div style="margin-bottom:30px;">
        <h2 style="color:#1f2937; border-bottom:1px solid #e5e7eb; padding-bottom:10px;">📊 Dashboard Summary</h2>
        ${document.getElementById('statsBox').innerHTML}
        ${document.getElementById('kpis') ? document.getElementById('kpis').innerHTML : ''}
      </div>
      
      <div style="margin-bottom:30px; page-break-inside:avoid;">
        <h2 style="color:#1f2937; border-bottom:1px solid #e5e7eb; padding-bottom:10px;">👥 Teams Performance</h2>
        ${document.getElementById('teamTable').innerHTML}
      </div>
      
      <div style="margin-bottom:30px; page-break-inside:avoid;">
        <h2 style="color:#1f2937; border-bottom:1px solid #e5e7eb; padding-bottom:10px;">📈 Total Progress</h2>
        ${document.getElementById('totalTable').innerHTML}
      </div>
      
      <div style="margin-bottom:30px; page-break-inside:avoid;">
        <h2 style="color:#1f2937; border-bottom:1px solid #e5e7eb; padding-bottom:10px;">📋 Statistics</h2>
        ${document.getElementById('statisticsContent') ? document.getElementById('statisticsContent').innerHTML : ''}
      </div>
      
      <div style="margin-bottom:30px; page-break-inside:avoid;">
        <h2 style="color:#1f2937; border-bottom:1px solid #e5e7eb; padding-bottom:10px;">🗺️ Project Map</h2>
        <img src="https://gisdatam.github.io/Map/preview.png" 
             style="width:100%; max-width:800px; display:block; margin:0 auto; border:1px solid #ccc;"
             alt="Project Map">
        <p style="text-align:center; color:#6b7280; margin-top:10px;">
          Interactive map available at: https://gisdatam.github.io/Map/
        </p>
      </div>
      
      <div style="margin-top:50px; padding-top:20px; border-top:2px solid #ccc; color:#6b7280; font-size:12px;">
        <p>Report generated by NDC Dashboard System</p>
        <p>Confidential - For internal use only</p>
      </div>
    </div>
  `;
  
  // إعادة عرض التبويب الحالي فقط
  document.querySelectorAll('.tab-content').forEach(tab => {
    tab.style.display = 'none';
  });
  if (currentTab) {
    currentTab.style.display = 'block';
  }
  
  return report;
}

// ========== EXPORT PDF ==========
function exportPDF() {
  console.log("تصدير PDF...");
  
  const report = buildReport();
  if (!report) {
    alert("فشل في بناء التقرير");
    return;
  }
  
  report.style.display = "block";
  
  html2canvas(report, {
    scale: 2,
    useCORS: true,
    logging: true,
    backgroundColor: "#ffffff"
  }).then(canvas => {
    const imgData = canvas.toDataURL('image/png');
    const pdf = new jspdf.jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4'
    });
    
    const imgWidth = 210; // A4 width in mm
    const pageHeight = 297; // A4 height in mm
    const imgHeight = canvas.height * imgWidth / canvas.width;
    
    let heightLeft = imgHeight;
    let position = 0;
    
    pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
    heightLeft -= pageHeight;
    
    // إضافة صفحات إضافية إذا كان التقرير طويلاً
    while (heightLeft >= 0) {
      position = heightLeft - imgHeight;
      pdf.addPage();
      pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
      heightLeft -= pageHeight;
    }
    
    pdf.save(`NDC_Report_${new Date().toISOString().slice(0,10)}.pdf`);
    report.style.display = "none";
    alert("تم تصدير التقرير بنجاح!");
  }).catch(error => {
    console.error("خطأ في تصدير PDF:", error);
    alert("حدث خطأ أثناء تصدير PDF");
    report.style.display = "none";
  });
}

// ========== EXPORT PNG ==========
function exportPNG() {
  console.log("تصدير PNG...");
  
  const report = buildReport();
  if (!report) {
    alert("فشل في بناء التقرير");
    return;
  }
  
  report.style.display = "block";
  
  html2canvas(report, {
    scale: 2,
    useCORS: true,
    logging: false,
    backgroundColor: "#ffffff"
  }).then(canvas => {
    const link = document.createElement('a');
    link.download = `NDC_Report_${new Date().toISOString().slice(0,10)}.png`;
    link.href = canvas.toDataURL('image/png');
    link.click();
    
    report.style.display = "none";
    alert("تم تصدير الصورة بنجاح!");
  }).catch(error => {
    console.error("خطأ في تصدير PNG:", error);
    alert("حدث خطأ أثناء تصدير PNG");
    report.style.display = "none";
  });
}

// ========== EXPORT EXCEL ==========
function exportExcel() {
  if (!window.masterData || window.masterData.length === 0) {
    alert("لا توجد بيانات للتصدير");
    return;
  }
  
  try {
    const ws = XLSX.utils.json_to_sheet(window.masterData);
    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, ws, "NDC_Data");
    
    XLSX.writeFile(wb, `NDC_Data_${new Date().toISOString().slice(0,10)}.xlsx`);
    alert("تم تصدير بيانات Excel بنجاح!");
  } catch (error) {
    console.error("خطأ في تصدير Excel:", error);
    alert("حدث خطأ أثناء تصدير Excel");
  }
}